{{- range .Values.ingress.hosts }}
apiVersion: v1
kind: Service
metadata:
# {{.}}
  name: {{ print "svc-" .name | trunc 63 | trimSuffix "-" }}
  labels:
  {{- include "nginx-reverse-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
      {{- include "nginx-reverse-proxy.labels" . | nindent 8 }}
---
{{- end }}