apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-uri
  labels:
    {{- include "vehiclescraper.labels" . | nindent 4 }}
data:
  URI: {{printf "mongodb://%s:27017" (include "vehiclescraper.mongoFullName" .)|quote}}

