apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    {{- include "vehiclescraper.labels" . | nindent 4 }}
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 24Gi
    storageClassName: {{ .Values.storageClass }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  storageClassName: {{ .Values.storageClass }}
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb