apiVersion: v1
kind: Secret
metadata:
    name: {{ include "vehiclescraper.pullSecretName" .}}
    labels:
    {{- include "vehiclescraper.labels" . | nindent 8 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}},\"currentContext\":\"rootless\"}" .Values.ghcrToken | b64enc| quote }}
