apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "picoshare.fullname" . }}
  labels:
    {{- include "picoshare.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "picoshare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "picoshare.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "picoshare.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "mtlynch/picoshare"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4001
              protocol: TCP
          env:
            - name: PS_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "picoshare.fullname" . }}
                  key: PS_SHARED_SECRET
            - name: PS_PORT
              value: "4001"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "picoshare.fullname" . }}
