apiVersion: v1
kind: Secret
metadata:
  name: {{ include "picoshare.fullname" . }}
  labels:
    {{- include "picoshare.labels" . | nindent 4 }}
type: Opaque
data:
  PS_SHARED_SECRET: {{ .Values.sharedSecret | b64enc }}
