apiVersion: v1
kind: Service
metadata:
  name: {{ include "picoshare.fullname" . }}
  labels:
    {{- include "picoshare.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: web
  selector:
    {{- include "picoshare.selectorLabels" . | nindent 4 }}
