apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "picoshare.fullname" . }}
  labels:
    {{- include "picoshare.labels" . | nindent 4 }}
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
