apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Release.Name }}-pv
    labels:
        app: {{ .Release.Name }}
        type: local
spec:
    storageClassName: {{ .Values.persistence.storageClass }}
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: {{ .Values.persistence.path }}