apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}-pvc
    labels:
        app: {{ .Release.Name }}
spec:
    storageClassName: {{ .Values.persistence.storageClass }}
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 16Gi