apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}
    labels:
        app: {{ .Release.Name }}
spec:
    storageClassName: openebs-hostpath
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi