apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
data:
  .dockerconfigjson: {{
    printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}},\"currentContext\":\"rootless\"}" .Values.ghcrToken
     | b64enc 
     | quote 
     }}
type: kubernetes.io/dockerconfigjson