apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stirling-pdf
  labels:
    {{- include "stirling-pdf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
