apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privatebin-pvc
  labels:
    {{- include "privatebin.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
