apiVersion: v1
kind: Service
metadata:
  name: privatebin-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: privatebin
  type: ClusterIP